/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gha.sample;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SampleTest {
    @Test
    void test() {
        final var actual = 1 + 1;
        assertEquals(3, actual);
    }
}
