/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gha.sample;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class SampleTest {
    @Test
    void test() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
